language: node_js
node_js:
    - 12.13.1
before_install:
    - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb
    - sudo dpkg -i --force-confnew elasticsearch-7.5.1-amd64.deb
    - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
    - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
    - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
    - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
    - sudo systemctl start elasticsearch
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - sleep 10
after_script:
    - ./cc-test-reporter after-build
    - pkill node
env:
    global:
        - NODE_ENV=test
        - PROTOCOL=http
        - HOSTNAME=localhost
        - PORT=8888
        - ELASTICSEARCH_PROTOCOL=http
        - ELASTICSEARCH_HOSTNAME=localhost
        - ELASTICSEARCH_PORT=9200
        - ELASTICSEARCH_INDEX=test
